### ISSUE TITLE
Latest data 'Configuration' host left-click link wont open up 'popup' configuration for host  - Zabbix 6.0

### ISSUE THREAD

**Issue by jamescook000** [BGmot/zabbix-module-latest-data#3]
Trying to open up the host configuration by left-clicking on the host and selecting 'Configuration' in latest data wont open up the host configuration popup for the host.

**Comment by BGmot** [comment]
Fixed in https://github.com/BGmot/zabbix-module-latest-data/tree/v3.0.1 please test.

**Comment by jamescook000** [comment]
Hi,

I tried using branch v3.0.1 for Zabbix 6.0.X and it reports 'Unable to load module'.

However I have manually put your code changes in yesterdays commits in place and can confirm they work and the host configuration will now open, so thanks.

I guess the code for 6.0.X needs to have its own branch based off tag v2.0.1 with yesterdays changes as there is some form of incompatibility.

Regards
James

**Comment by BGmot** [comment]
Yes according to https://github.com/BGmot/zabbix-module-latest-data#readme you should be using v2.0.1 for Zabbix 6.0. I did not make these changes for this version. Will do.

**Comment by BGmot** [comment]
Fixed in https://github.com/BGmot/zabbix-module-latest-data/tree/v2.0.2

**Comment by jamescook000** [comment]
Hi BGmot,

I tried v2.0.2 and found the same issue remains.

I put the code changes in again manually in the meantime with v2.0.1

Regards
James

**Comment by BGmot** [comment]
I tested and everything looks good to me with Zabbix 6.0 and v2.0.2.
Can you please make sure you have correct file
```

**Comment by jamescook000** [comment]
Hi,
Sorry yes this does work. I was also checking for the specific host latest data (https://github.com/BGmot/zabbix-module-latest-data/issues/2)....
Regards
James
